# Generated by Django 4.1.2 on 2022-10-23 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('persona_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('ap_paterno', models.CharField(blank=True, max_length=25, null=True)),
                ('ap_materno', models.CharField(blank=True, max_length=25, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('dir_num', models.CharField(blank=True, max_length=4, null=True)),
                ('calle', models.CharField(blank=True, max_length=25, null=True)),
                ('colonia', models.CharField(blank=True, max_length=25, null=True)),
                ('delegacion', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('municipio', models.CharField(blank=True, max_length=25, null=True)),
                ('estado', models.CharField(blank=True, max_length=25, null=True)),
                ('pais', models.CharField(blank=True, max_length=25, null=True)),
                ('correo', models.CharField(blank=True, max_length=40, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('curp', models.CharField(blank=True, max_length=28, null=True)),
                ('fecha_reg', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('tarea_id', models.IntegerField(primary_key=True, serialize=False)),
                ('info_add', models.CharField(blank=True, max_length=50, null=True)),
                ('dir_archivo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('costo', models.IntegerField(blank=True, null=True)),
                ('fecha_ini', models.DateTimeField(blank=True, null=True)),
                ('fecha_lim', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoClie',
            fields=[
                ('tipo_clie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_c', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'tipo_clie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmp',
            fields=[
                ('tipo_emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_e', models.CharField(blank=True, max_length=25, null=True)),
                ('permisos', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'tipo_emp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('tramite_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=25, null=True)),
                ('descrip', models.CharField(blank=True, max_length=100, null=True)),
                ('requisitos', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'tramite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personas')),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personas')),
                ('permisos_add', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsigEmpClie',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='clientes')),
            ],
            options={
                'db_table': 'asig_emp_clie',
                'managed': False,
            },
        ),
    ]