# Generated by Django 4.1.2 on 2022-11-15 06:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Clie_Asig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ap_paterno', models.CharField(max_length=25)),
                ('ap_materno', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('dir_num', models.IntegerField()),
                ('calle', models.CharField(max_length=25)),
                ('colonia', models.CharField(max_length=25)),
                ('delegacion', models.CharField(max_length=25)),
                ('cod_postal', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^\\d{5}$')])),
                ('municipio', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=25)),
                ('pais', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=40)),
                ('estado_civil', models.CharField(choices=[('S', 'SOLTERO(A)'), ('C', 'CASADO(A)'), ('D', 'DIVORSIADO(A)'), ('V', 'VIUDO(A)')], default='S', max_length=1)),
                ('fecha_nac', models.DateField()),
                ('rfc', models.CharField(max_length=13)),
                ('curp', models.CharField(max_length=28)),
                ('fecha_reg', models.DateField()),
            ],
            options={
                'db_table': 'personas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoClie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_c', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'tipo_clie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_e', models.CharField(blank=True, max_length=25, null=True)),
                ('permisos', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'tipo_emp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=25, null=True)),
                ('descrip', models.CharField(blank=True, max_length=100, null=True)),
                ('requisitos', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'tramite',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sat.personas')),
                ('tipo_clie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sat.tipoclie')),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sat.personas')),
                ('permisos_add', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('clie_s', models.ManyToManyField(through='sat.Emp_Clie_Asig', to='sat.clientes')),
                ('tipo_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sat.tipoemp')),
            ],
            options={
                'db_table': 'empleados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_add', models.CharField(blank=True, max_length=50, null=True)),
                ('dir_archivo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(max_length=10)),
                ('costo', models.IntegerField(default=0)),
                ('fecha_ini', models.DateTimeField()),
                ('fecha_lim', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('emp_clie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat.emp_clie_asig')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat.tramite')),
                ('emp_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat.empleados')),
            ],
            options={
                'db_table': 'tarea',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='emp_clie_asig',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat.clientes'),
        ),
        migrations.AddField(
            model_name='emp_clie_asig',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sat.empleados'),
        ),
    ]
