# Generated by Django 4.1.3 on 2023-05-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='contra',
            field=models.CharField(max_length=1000, verbose_name='Contraseña'),
        ),
    ]
