# Generated by Django 4.1.3 on 2023-05-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='foto_perfil',
            field=models.ImageField(blank=True, max_length=5, null=True, upload_to='fotos_perfil/'),
        ),
    ]
