# Generated by Django 4.1.3 on 2023-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_documentos',
            name='archivos',
            field=models.ManyToManyField(related_name='archivos', to='sat.tipo_archivos', verbose_name='Archivos'),
        ),
    ]
