# Generated by Django 4.1.3 on 2023-05-04 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='cuenta_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
