# Generated by Django 4.1.2 on 2023-04-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_documentos',
            name='tipo_arch',
            field=models.ManyToManyField(related_name='archivos', to='sat.tipo_archivos'),
        ),
    ]
