# Generated by Django 4.1.2 on 2023-04-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0002_tipo_documentos_tipo_arch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_documentos',
            name='tipo_arch',
        ),
        migrations.AddField(
            model_name='tipo_documentos',
            name='archivos',
            field=models.ManyToManyField(related_name='archivos', to='sat.tipo_archivos', verbose_name='Archivos'),
        ),
    ]
