# Generated by Django 4.1.3 on 2023-05-05 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sat', '0002_personas_cuenta_usuario_delete_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='cuenta_usuario',
        ),
        migrations.CreateModel(
            name='Usuario_empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_id', to='sat.personas', verbose_name='Empleado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_id', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'usuario empleado',
                'verbose_name_plural': 'usuarios empleados',
                'db_table': 'usuario_empleado',
                'managed': True,
            },
        ),
    ]
