# Generated by Django 4.1.3 on 2023-05-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0002_personas_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
